# Generated by Django 6.0.2 on 2026-04-26 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Don',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_don', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('valide', models.BooleanField(default=False)),
                ('donneur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dons', to='comptes.donneur')),
                ('hopital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dons_recus', to='comptes.hopital')),
            ],
        ),
    ]
