# Generated by Django 6.0.2 on 2026-04-26 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
