# Generated by Django 6.0.2 on 2026-03-20 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campagne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('lieu', models.CharField(max_length=255)),
                ('groupes_cibles', models.CharField(max_length=100)),
                ('capacite_totale', models.PositiveIntegerField()),
                ('hopital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campagnes', to='comptes.hopital')),
            ],
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creneau_horaire', models.CharField(max_length=50)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('present', models.BooleanField(default=False)),
                ('campagne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='campagnes.campagne')),
                ('donneur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptes.donneur')),
            ],
            options={
                'unique_together': {('campagne', 'donneur')},
            },
        ),
    ]
