# Generated by Django 6.0.2 on 2026-04-26 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campagnes', '0001_initial'),
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campagne',
            name='hopital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campagnes', to='comptes.hopital'),
        ),
        migrations.AddField(
            model_name='inscription',
            name='campagne',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='campagnes.campagne'),
        ),
        migrations.AddField(
            model_name='inscription',
            name='donneur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptes.donneur'),
        ),
        migrations.AlterUniqueTogether(
            name='inscription',
            unique_together={('campagne', 'donneur')},
        ),
    ]
