# Generated by Django 6.0.4 on 2026-04-26 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campagnes', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campagne',
            name='capacite_totale',
        ),
        migrations.AddField(
            model_name='campagne',
            name='capacite_par_creneau',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='campagne',
            name='nb_creneaux',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='inscription',
            name='creneau_index',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
